/**
 * 疗愈语录库 + 失恋疗愈内容
 * 包含：1000条每日暖心话、失恋五阶段建议、情绪智能回复
 */

// ========== 每日暖心语录（1000条） ==========
export interface HealingQuote {
  text: string;
  category: 'warmth' | 'heartbreak' | 'self-love' | 'growth' | 'emotion' | 'life';
}

export const HEALING_QUOTES: HealingQuote[] = [
  // ===== 温暖治愈 (170条) =====
  { text: '你今天也很努力了，辛苦了。', category: 'warmth' },
  { text: '允许自己休息，不是每一天都需要全力以赴。', category: 'warmth' },
  { text: '你值得被温柔对待，尤其是被自己。', category: 'warmth' },
  { text: '慢慢来，花也是慢慢开的。', category: 'warmth' },
  { text: '没关系，今天不开心明天可以重新开始。', category: 'warmth' },
  { text: '你的存在本身就是一件美好的事。', category: 'warmth' },
  { text: '累了就靠一靠，世界不会因此塌下来。', category: 'warmth' },
  { text: '你不需要完美，只需要真实。', category: 'warmth' },
  { text: '今天的云很好看，你也是。', category: 'warmth' },
  { text: '难过的时候抱抱自己，你做得很好了。', category: 'warmth' },
  { text: '每一个小小的进步都值得被看见。', category: 'warmth' },
  { text: '温柔地对待自己，就像对待最好的朋友。', category: 'warmth' },
  { text: '你已经撑过了很多个难熬的日子，真的很棒。', category: 'warmth' },
  { text: '不必急着愈合，伤口也需要时间。', category: 'warmth' },
  { text: '你的感受很重要，不要忽略它们。', category: 'warmth' },
  { text: '即使步伐很小，你也在前进。', category: 'warmth' },
  { text: '今天也要好好吃饭，好好爱自己。', category: 'warmth' },
  { text: '你是被这个世界需要的人。', category: 'warmth' },
  { text: '不开心的事情会过去的，一定会的。', category: 'warmth' },
  { text: '给自己一个拥抱，你辛苦了。', category: 'warmth' },
  { text: '你不必讨好所有人，先讨好自己吧。', category: 'warmth' },
  { text: '下雨天也有下雨天的温柔。', category: 'warmth' },
  { text: '生活会慢慢变好的，你要相信。', category: 'warmth' },
  { text: '今天做不到也没关系，明天再试试看。', category: 'warmth' },
  { text: '你的眼泪不是软弱，是勇敢的证明。', category: 'warmth' },
  { text: '世界很大，但你的感受同样重要。', category: 'warmth' },
  { text: '深呼吸，把烦恼慢慢呼出去。', category: 'warmth' },
  { text: '你配得上所有温柔和美好。', category: 'warmth' },
  { text: '疲惫的时候，就让自己歇一歇吧。', category: 'warmth' },
  { text: '星星会在最暗的夜里最亮。', category: 'warmth' },
  { text: '你的每一天都在认真生活，这就够了。', category: 'warmth' },
  { text: '慢一点没关系，重要的是方向。', category: 'warmth' },
  { text: '今天的你已经足够好了。', category: 'warmth' },
  { text: '允许自己不那么坚强。', category: 'warmth' },
  { text: '有些路慢慢走，风景更好看。', category: 'warmth' },
  { text: '你笑起来的样子，是最好的模样。', category: 'warmth' },
  { text: '就算全世界都灰暗，你也是自己的光。', category: 'warmth' },
  { text: '不用和别人比，你有自己的节奏。', category: 'warmth' },
  { text: '你正在经历的一切，都会让你更强大。', category: 'warmth' },
  { text: '吃一颗糖，让今天甜一点点。', category: 'warmth' },
  { text: '你的温柔，世界都收到了。', category: 'warmth' },
  { text: '今晚好好睡一觉，明天又是新的一天。', category: 'warmth' },
  { text: '你值得拥有一段轻松的时光。', category: 'warmth' },
  { text: '偶尔脆弱一下，也没什么大不了。', category: 'warmth' },
  { text: '总有人在默默关心着你。', category: 'warmth' },
  { text: '每一个平凡的日子都值得被珍惜。', category: 'warmth' },
  { text: '你不孤单，有人和你一样在努力着。', category: 'warmth' },
  { text: '日子虽然平淡，但也藏着温暖。', category: 'warmth' },
  { text: '对自己说一声谢谢，因为你一直在坚持。', category: 'warmth' },
  { text: '别忘了，你也是别人眼中的光。', category: 'warmth' },
  { text: '哭完了就擦干眼泪，继续做自己。', category: 'warmth' },
  { text: '即使今天很难，你也挺过来了。', category: 'warmth' },
  { text: '你已经很勇敢了，不需要更多了。', category: 'warmth' },
  { text: '晚风很温柔，像在抚慰你的心。', category: 'warmth' },
  { text: '你的坚持终会开出花来。', category: 'warmth' },
  { text: '请记住，你永远不是一个人。', category: 'warmth' },
  { text: '日落之后，还有满天的星光等着你。', category: 'warmth' },
  { text: '你的善良和温柔，都会被这个世界温柔以待。', category: 'warmth' },
  { text: '不完美才是生活最真实的样子。', category: 'warmth' },
  { text: '别太为难自己了，你真的够努力了。', category: 'warmth' },
  { text: '每一次低谷都是在为下一次绽放蓄力。', category: 'warmth' },
  { text: '你的小小快乐，也是值得庆祝的事。', category: 'warmth' },
  { text: '生活不会一直下雨，总会放晴的。', category: 'warmth' },
  { text: '做自己就好，你本来就很好。', category: 'warmth' },
  { text: '你的心事可以慢慢说，我一直在。', category: 'warmth' },
  { text: '把目光放柔一些，世界也会柔软起来。', category: 'warmth' },
  { text: '今天也是值得被记住的一天。', category: 'warmth' },
  { text: '你比自己想象中更有力量。', category: 'warmth' },
  { text: '月亮也有阴晴圆缺，你也可以有起伏。', category: 'warmth' },
  { text: '泡一杯热茶，暖暖自己的心。', category: 'warmth' },
  { text: '你的脆弱也是你的一部分，接纳它吧。', category: 'warmth' },
  { text: '生活会给每一个认真的人一个拥抱。', category: 'warmth' },
  { text: '你走过的路，每一步都算数。', category: 'warmth' },
  { text: '阳光会穿过乌云照到你身上。', category: 'warmth' },
  { text: '不要急，好事都在慢慢来的路上。', category: 'warmth' },
  { text: '今天的风很轻，适合放下烦恼。', category: 'warmth' },
  { text: '你是独一无二的，不需要成为别人。', category: 'warmth' },
  { text: '即便世界喧嚣，也要守住内心的宁静。', category: 'warmth' },
  { text: '你的每一次微笑都在照亮世界。', category: 'warmth' },
  { text: '把不开心的事放一放，先吃点好吃的。', category: 'warmth' },
  { text: '有些美好正在来的路上，请耐心等待。', category: 'warmth' },
  { text: '你可以慢慢成长，不必匆匆忙忙。', category: 'warmth' },
  { text: '你的身边一直有爱，只是有时没注意到。', category: 'warmth' },
  { text: '今天不顺利没关系，明天还有机会。', category: 'warmth' },
  { text: '你值得被好好珍惜，首先是被自己。', category: 'warmth' },
  { text: '黑夜再长，也会迎来黎明。', category: 'warmth' },
  { text: '把心放宽一些，快乐就多一些。', category: 'warmth' },
  { text: '你是自己生命里最重要的人。', category: 'warmth' },
  { text: '别着急赶路，停下来看看风景也很好。', category: 'warmth' },
  { text: '你的努力不会白费，时间会给你答案。', category: 'warmth' },
  { text: '就算跌倒了，也要优雅地站起来。', category: 'warmth' },
  { text: '你的心里住着一个温暖的小太阳。', category: 'warmth' },
  { text: '难过是暂时的，美好会如约而至。', category: 'warmth' },
  { text: '对自己温柔一点，你值得拥有这份柔软。', category: 'warmth' },
  { text: '你已经在很多人心里种下了温暖。', category: 'warmth' },
  { text: '慢慢走，每一步都踩在春天里。', category: 'warmth' },
  { text: '你不需要向任何人证明自己。', category: 'warmth' },
  { text: '即使生活很苦，也别忘了给自己加点糖。', category: 'warmth' },
  { text: '你的存在让这个世界多了一份温柔。', category: 'warmth' },
  { text: '春天会来的，花会开的，你会好的。', category: 'warmth' },
  { text: '你可以哭，哭完之后天会更蓝。', category: 'warmth' },
  { text: '每天进步一点点就已经很了不起了。', category: 'warmth' },
  { text: '你的真诚是这个世界最珍贵的礼物。', category: 'warmth' },
  { text: '放过自己吧，你已经做得够好了。', category: 'warmth' },
  { text: '生活的小确幸一直都在，等你去发现。', category: 'warmth' },
  { text: '你像一朵花，慢慢开就好。', category: 'warmth' },
  { text: '不要害怕改变，每一次转变都是新生。', category: 'warmth' },
  { text: '你的内心有一片花园，别忘了浇水。', category: 'warmth' },
  { text: '今天的月亮很圆，祝你今夜好梦。', category: 'warmth' },
  { text: '你的善意终将回到你身边。', category: 'warmth' },
  { text: '接受不完美的自己，才能遇见更好的自己。', category: 'warmth' },
  { text: '你一直在被这个世界温柔以待。', category: 'warmth' },
  { text: '人生没有白走的路，每一步都有意义。', category: 'warmth' },
  { text: '你是值得被爱的，不要怀疑这一点。', category: 'warmth' },
  { text: '今天也要做一个温暖的人。', category: 'warmth' },
  { text: '请相信，你的未来充满无限可能。', category: 'warmth' },
  { text: '偶尔放空自己，也是一种充电。', category: 'warmth' },
  { text: '你已经走了很远的路，别忘了为自己鼓掌。', category: 'warmth' },
  { text: '生活不会辜负每一个认真生活的人。', category: 'warmth' },
  { text: '你的笑容是世界上最好的风景。', category: 'warmth' },
  { text: '再小的光也是光，你也在发光。', category: 'warmth' },
  { text: '万物皆有裂痕，那是光照进来的地方。', category: 'warmth' },
  { text: '你值得拥有一个温暖的冬天。', category: 'warmth' },
  { text: '不要忘记，你也曾是别人的希望。', category: 'warmth' },
  { text: '今天也许不完美，但一定有值得感恩的事。', category: 'warmth' },
  { text: '你正在慢慢变成更好的自己。', category: 'warmth' },
  { text: '把焦虑放下，去感受当下的美好。', category: 'warmth' },
  { text: '每一天都是一个全新的开始。', category: 'warmth' },
  { text: '你的心很柔软，请好好保护它。', category: 'warmth' },
  { text: '也许你看不到，但你正在被很多人爱着。', category: 'warmth' },
  { text: '今天的阳光是专门为你准备的。', category: 'warmth' },
  { text: '不必把所有事情都扛在自己肩上。', category: 'warmth' },
  { text: '你的每一个明天都会比今天更好。', category: 'warmth' },
  { text: '在这个世界上，你就是最好的你。', category: 'warmth' },
  { text: '给自己一点时间，一切都会好起来。', category: 'warmth' },
  { text: '你的温暖，足以融化所有的寒冷。', category: 'warmth' },
  { text: '你值得所有的美好不期而遇。', category: 'warmth' },
  { text: '别忘了抬头看看天空，它一直很辽阔。', category: 'warmth' },
  { text: '你的每一次呼吸都在证明你的勇气。', category: 'warmth' },
  { text: '用一颗柔软的心去拥抱这个世界。', category: 'warmth' },
  { text: '你不需要时刻坚强，柔软也是一种力量。', category: 'warmth' },
  { text: '你的故事还很长，别急着翻到最后。', category: 'warmth' },
  { text: '被雨淋湿也没关系，雨后会有彩虹。', category: 'warmth' },
  { text: '感谢你今天也在好好生活。', category: 'warmth' },
  { text: '你的心里有星星，别让乌云遮住它们。', category: 'warmth' },
  { text: '先照顾好自己，再去拥抱世界。', category: 'warmth' },
  { text: '你是一道光，温暖了很多人的路。', category: 'warmth' },
  { text: '世界偶尔冷漠，但你可以选择温暖。', category: 'warmth' },
  { text: '你的坚韧比你以为的要强大得多。', category: 'warmth' },
  { text: '带着希望入睡，怀着梦想起床。', category: 'warmth' },
  { text: '你的每一份善意都在让世界变好。', category: 'warmth' },
  { text: '把烦恼交给风吧，它会替你带走。', category: 'warmth' },
  { text: '你就是你自己最好的礼物。', category: 'warmth' },
  { text: '慢慢来，生活不是一场赛跑。', category: 'warmth' },
  { text: '你的真心，总会遇到懂得珍惜的人。', category: 'warmth' },
  { text: '今天也值得被温柔地记录下来。', category: 'warmth' },
  { text: '你的世界里也有很多小小的美好。', category: 'warmth' },
  { text: '不管怎样，你都在我心里闪闪发光。', category: 'warmth' },
  { text: '请允许好事慢慢发生。', category: 'warmth' },
  { text: '你不欠这个世界什么，先爱自己。', category: 'warmth' },
  { text: '你的眼睛里有星光，别让泪水蒙住了。', category: 'warmth' },
  { text: '有时候，什么都不做也是一种勇敢。', category: 'warmth' },
  { text: '你是这个冬天里最温暖的存在。', category: 'warmth' },
  { text: '一步一步来，每一步都有意义。', category: 'warmth' },
  { text: '你的心愿都在排队来找你。', category: 'warmth' },
  { text: '就算今天很难，你也没有放弃，真好。', category: 'warmth' },
  { text: '世界很美好，你也是其中最美的一部分。', category: 'warmth' },
  { text: '好好休息吧，明天的你会更有力量。', category: 'warmth' },
  { text: '你的每一滴泪都不会白流。', category: 'warmth' },
  { text: '你的人生没有标准答案，按自己的来就好。', category: 'warmth' },
  { text: '愿你被这个世界温柔相待。', category: 'warmth' },
  { text: '抬起头来，你会发现天空比想象中宽广。', category: 'warmth' },
  { text: '你的心值得被好好安放。', category: 'warmth' },

  // ===== 失恋疗愈 (170条) =====
  { text: '失去一段感情不代表失去爱的能力，你依然完整。', category: 'heartbreak' },
  { text: '那个人离开了，但你没有失去自己。', category: 'heartbreak' },
  { text: '心碎的声音，其实是心在重新生长。', category: 'heartbreak' },
  { text: '有些人注定是过客，而你注定是自己的归宿。', category: 'heartbreak' },
  { text: '放手不是放弃，是给自己一个重新开始的机会。', category: 'heartbreak' },
  { text: '你值得一个不需要你追赶的爱情。', category: 'heartbreak' },
  { text: '眼泪流完之后，你会发现自己比想象中坚强。', category: 'heartbreak' },
  { text: '离开错的人，才能遇见对的人。', category: 'heartbreak' },
  { text: '伤口总会愈合，而你会带着勋章继续前行。', category: 'heartbreak' },
  { text: '一个人也可以是一整个春天。', category: 'heartbreak' },
  { text: '你不是被抛弃了，你是被释放了。', category: 'heartbreak' },
  { text: '曾经的心动不会白费，它教会你如何去爱。', category: 'heartbreak' },
  { text: '没有谁离开了谁就活不下去，你远比你以为的强大。', category: 'heartbreak' },
  { text: '别用别人的离开来否定自己的价值。', category: 'heartbreak' },
  { text: '时间不会倒流，但伤痛会慢慢退潮。', category: 'heartbreak' },
  { text: '那些没有杀死你的，终将让你更懂爱。', category: 'heartbreak' },
  { text: '你的世界不会因为一个人的离开而崩塌。', category: 'heartbreak' },
  { text: '爱过就好，不必执着于结果。', category: 'heartbreak' },
  { text: '分开是为了让你找到更好的自己。', category: 'heartbreak' },
  { text: '心碎过后，你会拥有一颗更温柔的心。', category: 'heartbreak' },
  { text: '你值得被好好珍惜，而不是被轻易放下。', category: 'heartbreak' },
  { text: '他走了，但阳光还在，花还会开。', category: 'heartbreak' },
  { text: '不是所有的遗憾都需要被填满。', category: 'heartbreak' },
  { text: '学会和失去和平共处，是成长的一部分。', category: 'heartbreak' },
  { text: '你的快乐不应该寄托在任何一个人身上。', category: 'heartbreak' },
  { text: '一段感情的结束，不是你人生的结束。', category: 'heartbreak' },
  { text: '今天的心痛，是明天微笑的伏笔。', category: 'heartbreak' },
  { text: '有些告别，是命运在为你腾出更好的位置。', category: 'heartbreak' },
  { text: '你不需要另一个人来让自己变得完整。', category: 'heartbreak' },
  { text: '失恋不过是人生的一场暴风雨，雨后会有彩虹。', category: 'heartbreak' },
  { text: '与其怀念过去，不如期待未来。', category: 'heartbreak' },
  { text: '你的温柔值得被一个对的人接住。', category: 'heartbreak' },
  { text: '放下一个人，是对自己最大的温柔。', category: 'heartbreak' },
  { text: '爱情走了，自爱不能走。', category: 'heartbreak' },
  { text: '他不珍惜你，是他的损失，不是你的缺陷。', category: 'heartbreak' },
  { text: '独处也是一种浪漫，和自己好好相处吧。', category: 'heartbreak' },
  { text: '那些流过的泪，终将浇灌出更美的花。', category: 'heartbreak' },
  { text: '你没有做错什么，有些缘分就是有期限的。', category: 'heartbreak' },
  { text: '心会痛，但心也会自愈。', category: 'heartbreak' },
  { text: '不爱你的人留不住，爱你的人不会走。', category: 'heartbreak' },
  { text: '这段经历让你更懂得什么是真正值得的。', category: 'heartbreak' },
  { text: '别回头了，你的前方有更好的风景。', category: 'heartbreak' },
  { text: '一个人的旅程，也可以走得很精彩。', category: 'heartbreak' },
  { text: '伤疤是你勇敢爱过的证明。', category: 'heartbreak' },
  { text: '你配得上一份不让你流泪的感情。', category: 'heartbreak' },
  { text: '错过的人，是为了让你不再错过自己。', category: 'heartbreak' },
  { text: '没关系，慢慢来，伤口不急着愈合。', category: 'heartbreak' },
  { text: '你可以为他难过，但别为他停下脚步。', category: 'heartbreak' },
  { text: '爱自己是终身浪漫的开始。', category: 'heartbreak' },
  { text: '不被爱不代表不可爱，你本身就很好。', category: 'heartbreak' },
  { text: '总有一天你会感谢今天的放手。', category: 'heartbreak' },
  { text: '有些人是来教你成长的，不是来陪你一生的。', category: 'heartbreak' },
  { text: '分手是一扇关上的门，但窗户还开着。', category: 'heartbreak' },
  { text: '你的故事还很长，他只是其中一个章节。', category: 'heartbreak' },
  { text: '与其抓住不属于你的，不如拥抱属于你的。', category: 'heartbreak' },
  { text: '今天你为他哭泣，明天你会为自己骄傲。', category: 'heartbreak' },
  { text: '不是你不够好，只是你们不够合适。', category: 'heartbreak' },
  { text: '你的心很大，大到能装下整个世界的温柔。', category: 'heartbreak' },
  { text: '给自己时间，时间会给你答案。', category: 'heartbreak' },
  { text: '深呼吸，这一切都会过去的。', category: 'heartbreak' },
  { text: '破碎之后的重建，往往比从前更坚固。', category: 'heartbreak' },
  { text: '他缺席了你的未来，但你不会缺席自己的人生。', category: 'heartbreak' },
  { text: '被爱是运气，爱自己是本事。', category: 'heartbreak' },
  { text: '最好的复仇是让自己活得更好。', category: 'heartbreak' },
  { text: '每一次心碎都是一次重新认识自己的机会。', category: 'heartbreak' },
  { text: '你的眼泪很珍贵，别浪费在不值得的人身上。', category: 'heartbreak' },
  { text: '失去他，你还有整个世界。', category: 'heartbreak' },
  { text: '慢慢地，你会忘记他的样子，却记住自己的力量。', category: 'heartbreak' },
  { text: '有些爱，放在心里就好，不必再提起。', category: 'heartbreak' },
  { text: '你会再次心动的，在一个对的时间遇见对的人。', category: 'heartbreak' },
  { text: '痛过之后你会发现，一个人也挺好。', category: 'heartbreak' },
  { text: '不要因为一棵树，而放弃整片森林。', category: 'heartbreak' },
  { text: '你的价值不由任何人的去留来定义。', category: 'heartbreak' },
  { text: '接受失去，是通往新开始的第一步。', category: 'heartbreak' },
  { text: '你的笑容不应该因为任何人而消失。', category: 'heartbreak' },
  { text: '时间是最好的良药，请耐心等待。', category: 'heartbreak' },
  { text: '他不是你的全世界，你才是自己的全世界。', category: 'heartbreak' },
  { text: '这段感情教会了你爱，下一段会教你幸福。', category: 'heartbreak' },
  { text: '分开之后你会发现，自己一直都很好。', category: 'heartbreak' },
  { text: '不必急着翻篇，允许自己慢慢愈合。', category: 'heartbreak' },
  { text: '把对他的爱，转化为对自己的疼惜。', category: 'heartbreak' },
  { text: '你的未来不会因为失去一个人而暗淡。', category: 'heartbreak' },
  { text: '真正爱你的人，不会让你这么难过。', category: 'heartbreak' },
  { text: '你正在经历的痛苦，正在铸造一个更强大的你。', category: 'heartbreak' },
  { text: '即使心碎，也要记得给自己一个拥抱。', category: 'heartbreak' },
  { text: '那些深夜的眼泪，终会变成清晨的露珠。', category: 'heartbreak' },
  { text: '你可以想念他，但别忘了更爱自己。', category: 'heartbreak' },
  { text: '离开不适合你的人，是一种自我保护。', category: 'heartbreak' },
  { text: '所有的失去，都是另一种获得的开始。', category: 'heartbreak' },
  { text: '你的心碎了，但你的灵魂依然完好。', category: 'heartbreak' },
  { text: '感情的结束不是世界的尽头，而是新路的起点。', category: 'heartbreak' },
  { text: '你比任何一段感情都重要。', category: 'heartbreak' },
  { text: '今天很难，但明天会好一点，后天会更好。', category: 'heartbreak' },
  { text: '你不需要忘记他，只需要记住自己。', category: 'heartbreak' },
  { text: '让眼泪流完，然后擦干，继续走。', category: 'heartbreak' },
  { text: '旧的不去，新的不来，这是宇宙的善意。', category: 'heartbreak' },
  { text: '失恋是暂时的，而你的人生是永恒的。', category: 'heartbreak' },
  { text: '他错过了你，是他一辈子的遗憾。', category: 'heartbreak' },
  { text: '你值得一个不犹豫就选择你的人。', category: 'heartbreak' },
  { text: '把悲伤释放出来，别让它住在心里。', category: 'heartbreak' },
  { text: '你没有失去爱情，你只是暂时和它告别。', category: 'heartbreak' },
  { text: '单身不是惩罚，是重新出发的礼物。', category: 'heartbreak' },
  { text: '想哭就哭吧，哭完了天就亮了。', category: 'heartbreak' },
  { text: '你的温暖终会被一个懂得珍惜的人收藏。', category: 'heartbreak' },
  { text: '这个世界上最不该辜负的人，是你自己。', category: 'heartbreak' },
  { text: '他的离开，是你遇见更好的人的前奏。', category: 'heartbreak' },
  { text: '你值得一个让你安心的爱情。', category: 'heartbreak' },
  { text: '难过的时候就抬头看看天空，它一直都在。', category: 'heartbreak' },
  { text: '感情可以结束，但你对生活的热爱不能。', category: 'heartbreak' },
  { text: '你不是一个人在战斗，时间站在你这边。', category: 'heartbreak' },
  { text: '有些放手，是成全自己的幸福。', category: 'heartbreak' },
  { text: '爱错了人不可怕，可怕的是不敢再爱。', category: 'heartbreak' },
  { text: '你的心正在愈合，只是你还没察觉。', category: 'heartbreak' },
  { text: '别让一段过去的感情，偷走你现在的快乐。', category: 'heartbreak' },
  { text: '你的好，不需要别人的认可来证明。', category: 'heartbreak' },
  { text: '每一个日出都在告诉你，一切可以重新开始。', category: 'heartbreak' },
  { text: '比起被爱，学会爱自己更重要。', category: 'heartbreak' },
  { text: '你是自己最好的依靠，别忘了。', category: 'heartbreak' },
  { text: '旧伤口会结痂，新生活会发芽。', category: 'heartbreak' },
  { text: '你的幸福不需要任何人批准。', category: 'heartbreak' },
  { text: '哭过笑过之后，你会变成更好的自己。', category: 'heartbreak' },
  { text: '那些让你痛的，最终会让你更通透。', category: 'heartbreak' },
  { text: '没有人能带走你内心的光芒。', category: 'heartbreak' },
  { text: '你的人生剧本由你自己来写。', category: 'heartbreak' },
  { text: '允许自己悲伤，但别允许自己沉沦。', category: 'heartbreak' },
  { text: '等风来，等花开，等一个更好的未来。', category: 'heartbreak' },
  { text: '你值得被全心全意地对待。', category: 'heartbreak' },
  { text: '伤心是一阵子的，而成长是一辈子的。', category: 'heartbreak' },
  { text: '失恋让你哭泣，但时间会让你微笑。', category: 'heartbreak' },
  { text: '那个对的人正在来的路上，别急。', category: 'heartbreak' },
  { text: '你的心虽然受了伤，但它依然在跳动。', category: 'heartbreak' },
  { text: '不要用他的错来惩罚自己。', category: 'heartbreak' },
  { text: '你可以怀念过去，但要活在当下。', category: 'heartbreak' },
  { text: '一个人的夜晚也可以很温暖。', category: 'heartbreak' },
  { text: '你不欠任何人一段感情。', category: 'heartbreak' },
  { text: '跌倒了没关系，拍拍灰尘再站起来。', category: 'heartbreak' },
  { text: '你的泪水在浇灌一个更坚韧的自己。', category: 'heartbreak' },
  { text: '那段感情结束了，但你的精彩才刚开始。', category: 'heartbreak' },
  { text: '你的心足够宽广，能容纳悲伤也能拥抱希望。', category: 'heartbreak' },
  { text: '学会告别，是人生最重要的功课之一。', category: 'heartbreak' },
  { text: '你可以慢慢来，没有人催你痊愈。', category: 'heartbreak' },
  { text: '最深的伤痛过后，是最美的重生。', category: 'heartbreak' },
  { text: '爱情不是生活的全部，你还有很多值得期待。', category: 'heartbreak' },
  { text: '你没有输，你只是换了一条路。', category: 'heartbreak' },
  { text: '独自行走的路上，你会遇见真正的自己。', category: 'heartbreak' },
  { text: '别低头，皇冠会掉；别流泪，坏人会笑。', category: 'heartbreak' },
  { text: '你的善良和真诚，终会遇到对的人。', category: 'heartbreak' },
  { text: '把他还给人海，把自己还给自己。', category: 'heartbreak' },
  { text: '这世间的美好，远不止爱情一种。', category: 'heartbreak' },
  { text: '你正在变成一个更懂得爱与被爱的人。', category: 'heartbreak' },
  { text: '失去他不可怕，失去自己才可怕。', category: 'heartbreak' },
  { text: '你的生命力比你想象的更旺盛。', category: 'heartbreak' },
  { text: '那些痛苦的日子，正在悄悄变成过去式。', category: 'heartbreak' },
  { text: '不必急着走出来，允许自己在原地待一会儿。', category: 'heartbreak' },
  { text: '心碎是暂时的天气，而你是永恒的风景。', category: 'heartbreak' },
  { text: '你终将感谢那个勇敢放手的自己。', category: 'heartbreak' },
  { text: '所有的遇见和离别，都有它的意义。', category: 'heartbreak' },
  { text: '你在最难的时候，也在最接近光明的时候。', category: 'heartbreak' },
  { text: '温柔地对待自己的伤口，它会回报你力量。', category: 'heartbreak' },
  { text: '每一段结束的感情，都是通往幸福的路标。', category: 'heartbreak' },
  { text: '你的眼里不只有他，还有星辰大海。', category: 'heartbreak' },
  { text: '当你学会独处，你就不再害怕失去。', category: 'heartbreak' },
  { text: '心碎不是终点，而是蜕变的起点。', category: 'heartbreak' },
  { text: '你的坚强不是假装不痛，而是痛过之后依然前行。', category: 'heartbreak' },
  { text: '爱过的痕迹不会消失，它会变成你的铠甲。', category: 'heartbreak' },
  { text: '你值得一段不需要委屈自己的感情。', category: 'heartbreak' },
  { text: '夜再长也会天亮，冬再冷也会回春。', category: 'heartbreak' },
  { text: '你的生活不会因为少了一个人而褪色。', category: 'heartbreak' },
  { text: '允许自己脆弱，也要记得自己的勇敢。', category: 'heartbreak' },
  { text: '走出失恋的那一天，你会感谢今天的自己。', category: 'heartbreak' },
  { text: '爱自己，是给未来最好的礼物。', category: 'heartbreak' },

  // ===== 自我肯定 (170条) =====
  { text: '你比自己想象的更强大。', category: 'self-love' },
  { text: '爱自己是终身浪漫的开始。', category: 'self-love' },
  { text: '接受不完美的自己，是最大的勇气。', category: 'self-love' },
  { text: '你值得被温柔以待。', category: 'self-love' },
  { text: '允许自己慢慢来，不必急于证明什么。', category: 'self-love' },
  { text: '你的存在本身就是一份礼物。', category: 'self-love' },
  { text: '对自己温柔一点，你已经很努力了。', category: 'self-love' },
  { text: '不必讨好任何人，你本身就很好。', category: 'self-love' },
  { text: '学会拥抱自己的脆弱。', category: 'self-love' },
  { text: '每一天都是重新爱自己的机会。', category: 'self-love' },
  { text: '你的感受永远值得被重视。', category: 'self-love' },
  { text: '放下自我批判，拥抱自我成长。', category: 'self-love' },
  { text: '你已经足够好了，不需要任何人的认可。', category: 'self-love' },
  { text: '善待自己，是对生命最好的尊重。', category: 'self-love' },
  { text: '你的光芒不会因为别人的否定而黯淡。', category: 'self-love' },
  { text: '允许自己休息，这不是懒惰。', category: 'self-love' },
  { text: '你值得拥有一切美好的事物。', category: 'self-love' },
  { text: '先成为自己的太阳，再去温暖别人。', category: 'self-love' },
  { text: '接纳自己的情绪，它们都是真实的。', category: 'self-love' },
  { text: '你的价值不由他人定义。', category: 'self-love' },
  { text: '勇敢地做自己，世界会为你让路。', category: 'self-love' },
  { text: '爱自己不是自私，而是自救。', category: 'self-love' },
  { text: '你配得上所有的幸福和快乐。', category: 'self-love' },
  { text: '每一个伤疤都是成长的勋章。', category: 'self-love' },
  { text: '你的内心比你知道的更有力量。', category: 'self-love' },
  { text: '不要为了迎合别人而委屈自己。', category: 'self-love' },
  { text: '学会和自己和解，是最深的治愈。', category: 'self-love' },
  { text: '你是自己最好的朋友。', category: 'self-love' },
  { text: '允许自己不够好，这也是一种勇敢。', category: 'self-love' },
  { text: '先学会爱自己，才能更好地爱别人。', category: 'self-love' },
  { text: '你不欠任何人一个解释。', category: 'self-love' },
  { text: '接受自己的节奏，不必和别人比较。', category: 'self-love' },
  { text: '相信自己，你有无限可能。', category: 'self-love' },
  { text: '你的心值得被好好呵护。', category: 'self-love' },
  { text: '不必为过去的自己感到抱歉。', category: 'self-love' },
  { text: '你有权利说不，这是自爱的表现。', category: 'self-love' },
  { text: '你的眼泪也是一种力量。', category: 'self-love' },
  { text: '做自己喜欢的事，成为自己喜欢的人。', category: 'self-love' },
  { text: '你值得被认真对待。', category: 'self-love' },
  { text: '放过自己，也是一种成全。', category: 'self-love' },
  { text: '你的每一步都算数。', category: 'self-love' },
  { text: '不完美才是真实，真实才是美丽。', category: 'self-love' },
  { text: '你是自己生命中最重要的人。', category: 'self-love' },
  { text: '允许自己脆弱，脆弱中蕴藏着力量。', category: 'self-love' },
  { text: '你的世界因你而精彩。', category: 'self-love' },
  { text: '别忘了，你也需要被照顾。', category: 'self-love' },
  { text: '你有选择幸福的权利。', category: 'self-love' },
  { text: '真正的强大是敢于面对真实的自己。', category: 'self-love' },
  { text: '你不需要变成别人眼中的样子。', category: 'self-love' },
  { text: '你的善良不应该成为别人伤害你的理由。', category: 'self-love' },
  { text: '学会给自己鼓掌，你已经很棒了。', category: 'self-love' },
  { text: '你的内心有一片属于自己的花园。', category: 'self-love' },
  { text: '不要因为害怕失去而放弃自己。', category: 'self-love' },
  { text: '你的快乐不需要经过别人的同意。', category: 'self-love' },
  { text: '温柔对待自己的每一个念头。', category: 'self-love' },
  { text: '你值得一份不将就的人生。', category: 'self-love' },
  { text: '拒绝内耗，选择自爱。', category: 'self-love' },
  { text: '你的独特是最珍贵的财富。', category: 'self-love' },
  { text: '允许自己犯错，错误是最好的老师。', category: 'self-love' },
  { text: '你不必承担所有人的期待。', category: 'self-love' },
  { text: '学会为自己撑伞，不必等谁来遮风挡雨。', category: 'self-love' },
  { text: '你的存在让这个世界更美好。', category: 'self-love' },
  { text: '做真实的自己，比做完美的别人更重要。', category: 'self-love' },
  { text: '你有权利追求自己想要的生活。', category: 'self-love' },
  { text: '别让任何人偷走你的自信。', category: 'self-love' },
  { text: '你是自己故事里的主角。', category: 'self-love' },
  { text: '爱自己从接受自己的缺点开始。', category: 'self-love' },
  { text: '你的努力终将开花结果。', category: 'self-love' },
  { text: '不要小看自己，你拥有改变的力量。', category: 'self-love' },
  { text: '给自己一些时间，花开自有花期。', category: 'self-love' },
  { text: '你的人生不需要和任何人比较。', category: 'self-love' },
  { text: '勇敢地设立边界，保护自己的能量。', category: 'self-love' },
  { text: '你的心声值得被倾听。', category: 'self-love' },
  { text: '不必为了合群而丢掉自己。', category: 'self-love' },
  { text: '你值得一段不委屈的感情。', category: 'self-love' },
  { text: '你已经走了很远，别忘了为自己骄傲。', category: 'self-love' },
  { text: '学会取悦自己，而不是讨好别人。', category: 'self-love' },
  { text: '你的柔软不是弱点，而是力量。', category: 'self-love' },
  { text: '拥抱不确定性，这是成长的一部分。', category: 'self-love' },
  { text: '你比任何困难都强大。', category: 'self-love' },
  { text: '允许自己享受当下的美好。', category: 'self-love' },
  { text: '你的人生由你自己书写。', category: 'self-love' },
  { text: '不必为真实的自己感到羞耻。', category: 'self-love' },
  { text: '你是值得被爱的，从来都是。', category: 'self-love' },
  { text: '对自己诚实，是最高级的自爱。', category: 'self-love' },
  { text: '你的能量应该留给值得的事。', category: 'self-love' },
  { text: '慢慢来，一切都来得及。', category: 'self-love' },
  { text: '你不需要向任何人证明自己的价值。', category: 'self-love' },
  { text: '接住自己的情绪，不评判不逃避。', category: 'self-love' },
  { text: '你的坚强不需要掌声来验证。', category: 'self-love' },
  { text: '爱自己是一场没有终点的旅行。', category: 'self-love' },
  { text: '你有能力创造自己想要的生活。', category: 'self-love' },
  { text: '允许自己被感动，被治愈。', category: 'self-love' },
  { text: '你的生命有自己的时区，不必着急。', category: 'self-love' },
  { text: '不要把别人的评价当作镜子。', category: 'self-love' },
  { text: '你值得被好好珍惜，包括被自己。', category: 'self-love' },
  { text: '学会放手不适合的，留住珍贵的。', category: 'self-love' },
  { text: '你的每一次尝试都值得肯定。', category: 'self-love' },
  { text: '真正的自由是做真实的自己。', category: 'self-love' },
  { text: '不必事事追求完美，够好就好。', category: 'self-love' },
  { text: '你的内心深处藏着无尽的宝藏。', category: 'self-love' },
  { text: '给自己的生活留一些空白。', category: 'self-love' },
  { text: '你的伤痛终会变成你的铠甲。', category: 'self-love' },
  { text: '学会在孤独中与自己相处。', category: 'self-love' },
  { text: '你是自己最温暖的港湾。', category: 'self-love' },
  { text: '不要让恐惧阻止你成为更好的自己。', category: 'self-love' },
  { text: '你的声音有被听到的价值。', category: 'self-love' },
  { text: '每一次深呼吸都是对自己的关爱。', category: 'self-love' },
  { text: '你不必永远坚强，偶尔示弱也没关系。', category: 'self-love' },
  { text: '选择善待自己，是最明智的决定。', category: 'self-love' },
  { text: '你的灵魂值得被温柔守护。', category: 'self-love' },
  { text: '勇于接受帮助，不是软弱的表现。', category: 'self-love' },
  { text: '你一直在成长，即使自己没有察觉。', category: 'self-love' },
  { text: '不必为了别人的期望而活。', category: 'self-love' },
  { text: '你的未来充满无限美好。', category: 'self-love' },
  { text: '学会在平凡中发现自己的闪光点。', category: 'self-love' },
  { text: '你是一道独特的风景线。', category: 'self-love' },
  { text: '允许自己重新开始，多少次都可以。', category: 'self-love' },
  { text: '你的幸福由自己决定。', category: 'self-love' },
  { text: '不完美的你，依然值得被爱。', category: 'self-love' },
  { text: '你有权利活出自己想要的模样。', category: 'self-love' },
  { text: '对过去的自己说声谢谢。', category: 'self-love' },
  { text: '你的每一天都在变得更好。', category: 'self-love' },
  { text: '学会在风雨中为自己撑一把伞。', category: 'self-love' },
  { text: '你是值得被等待的人。', category: 'self-love' },
  { text: '不必解释自己的选择，你懂就好。', category: 'self-love' },
  { text: '你的心里有一片星辰大海。', category: 'self-love' },
  { text: '允许自己按自己的方式生活。', category: 'self-love' },
  { text: '你的温暖值得留一些给自己。', category: 'self-love' },
  { text: '把自己当作最重要的人来爱护。', category: 'self-love' },
  { text: '你已经很勇敢了，请继续相信自己。', category: 'self-love' },
  { text: '不必追赶别人的脚步，走好自己的路。', category: 'self-love' },
  { text: '你有拒绝的权利，不必感到愧疚。', category: 'self-love' },
  { text: '你的每一面都值得被欣赏。', category: 'self-love' },
  { text: '学会在安静中听见自己内心的声音。', category: 'self-love' },
  { text: '你是自己最好的治愈者。', category: 'self-love' },
  { text: '不要因为别人的无知而否定自己。', category: 'self-love' },
  { text: '你配得上所有的赞美和掌声。', category: 'self-love' },
  { text: '接受今天的自己，期待明天的成长。', category: 'self-love' },
  { text: '你的坚持终将被岁月温柔以待。', category: 'self-love' },
  { text: '爱自己就是最好的答案。', category: 'self-love' },
  { text: '你不需要活在别人的目光里。', category: 'self-love' },
  { text: '保护好自己的能量场。', category: 'self-love' },
  { text: '你的存在就是最好的证明。', category: 'self-love' },
  { text: '对自己宽容一些，你做得很好。', category: 'self-love' },
  { text: '你有权利为自己感到骄傲。', category: 'self-love' },
  { text: '不要忽略自己内心真正的需要。', category: 'self-love' },
  { text: '你的眼睛里有星星，别让它暗下去。', category: 'self-love' },
  { text: '学会把自己放在第一位。', category: 'self-love' },
  { text: '你永远有重新出发的勇气。', category: 'self-love' },
  { text: '做一个让自己满意的人就够了。', category: 'self-love' },
  { text: '你的路虽远，但每一步都有意义。', category: 'self-love' },
  { text: '允许自己被爱，也允许自己去爱。', category: 'self-love' },
  { text: '你的孤独也有花开的力量。', category: 'self-love' },
  { text: '不必强迫自己合群，独处也很美好。', category: 'self-love' },
  { text: '你是自己命运的掌舵者。', category: 'self-love' },
  { text: '给自己一个微笑，今天也要加油。', category: 'self-love' },
  { text: '你无需他人的许可来做自己。', category: 'self-love' },
  { text: '你的沉默也是一种力量。', category: 'self-love' },
  { text: '学会原谅自己，然后轻装前行。', category: 'self-love' },
  { text: '你值得拥有内心的平静。', category: 'self-love' },
  { text: '不要把自己的需求排在最后。', category: 'self-love' },
  { text: '你一直比自己以为的更优秀。', category: 'self-love' },
  { text: '把时间花在让自己变好的事情上。', category: 'self-love' },
  { text: '你是这个世界上独一无二的存在。', category: 'self-love' },
  { text: '自我关怀不是奢侈，而是必需。', category: 'self-love' },
  { text: '你的故事还在继续，别急着翻篇。', category: 'self-love' },
  { text: '永远不要低估自己的力量。', category: 'self-love' },

  // ===== 成长感悟 (170条) =====
  { text: '痛苦是成长的催化剂，不是终点。', category: 'growth' },
  { text: '每一次跌倒，都是学会站起来的机会。', category: 'growth' },
  { text: '勇敢不是不害怕，而是害怕了还选择前行。', category: 'growth' },
  { text: '成长从来都不是舒适的，但永远是值得的。', category: 'growth' },
  { text: '裂缝是光照进来的地方。', category: 'growth' },
  { text: '每一段弯路，都是必经之路。', category: 'growth' },
  { text: '允许自己不够好，是变好的开始。', category: 'growth' },
  { text: '种子在黑暗中才能发芽。', category: 'growth' },
  { text: '你正在成为你需要的那个人。', category: 'growth' },
  { text: '失败不是结局，放弃才是。', category: 'growth' },
  { text: '所有的经历都在塑造更好的你。', category: 'growth' },
  { text: '接纳不完美，才是真正的强大。', category: 'growth' },
  { text: '今天的泪水，是明天的力量。', category: 'growth' },
  { text: '成长是一场没有观众的独舞。', category: 'growth' },
  { text: '伤疤是你战胜困难的勋章。', category: 'growth' },
  { text: '耐心等待，花自然会开。', category: 'growth' },
  { text: '你比你以为的更坚强。', category: 'growth' },
  { text: '每一次选择都在重新定义你自己。', category: 'growth' },
  { text: '不要急，你的时区刚刚好。', category: 'growth' },
  { text: '蜕变的过程总是伴随着不适。', category: 'growth' },
  { text: '走过的每一步，都算数。', category: 'growth' },
  { text: '困难是化了妆的礼物。', category: 'growth' },
  { text: '你值得拥有更好的自己。', category: 'growth' },
  { text: '迷茫说明你正在思考，焦虑说明你想要改变。', category: 'growth' },
  { text: '真正的成长，是学会与自己和解。', category: 'growth' },
  { text: '没有白走的路，每一步都有意义。', category: 'growth' },
  { text: '破茧成蝶之前，要先忍受黑暗。', category: 'growth' },
  { text: '你的脆弱里藏着巨大的力量。', category: 'growth' },
  { text: '进步不需要轰轰烈烈，微小的改变也是改变。', category: 'growth' },
  { text: '学会放下，才能腾出手拥抱新的可能。', category: 'growth' },
  { text: '每个冬天的尽头，都有一个春天在等待。', category: 'growth' },
  { text: '成熟是经历痛苦后依然温柔。', category: 'growth' },
  { text: '你不是在原地踏步，你是在扎根。', category: 'growth' },
  { text: '坚持不是因为看到希望，而是坚持后才有希望。', category: 'growth' },
  { text: '人生没有白受的苦，每一种痛都有回响。', category: 'growth' },
  { text: '允许自己休息，也是一种勇敢。', category: 'growth' },
  { text: '你的故事还没写完，别急着下结论。', category: 'growth' },
  { text: '真正的力量，来自于温柔地面对脆弱。', category: 'growth' },
  { text: '每一次告别，都是为了更好的重逢。', category: 'growth' },
  { text: '你不需要别人的认可来证明自己的价值。', category: 'growth' },
  { text: '成长是把哭声调成静音的过程。', category: 'growth' },
  { text: '即使步伐很小，也在靠近目标。', category: 'growth' },
  { text: '所有的不甘心，终将化为前行的动力。', category: 'growth' },
  { text: '你现在的迷茫，是未来清醒的伏笔。', category: 'growth' },
  { text: '弯路走多了，也就成了捷径。', category: 'growth' },
  { text: '接受改变，是成长的第一课。', category: 'growth' },
  { text: '生活的裂痕里，开出了最坚韧的花。', category: 'growth' },
  { text: '你可以慢，但不要停。', category: 'growth' },
  { text: '暴风雨过后，你还站在这里，这就是胜利。', category: 'growth' },
  { text: '向内探索，比向外追寻更有力量。', category: 'growth' },
  { text: '不完美的开始，胜过完美的等待。', category: 'growth' },
  { text: '你的每一份努力，时间都会给出答案。', category: 'growth' },
  { text: '有些路必须一个人走，才能找到自己。', category: 'growth' },
  { text: '成长的代价是失去旧的自己。', category: 'growth' },
  { text: '此刻的犹豫，终会变成未来的果断。', category: 'growth' },
  { text: '接纳昨天的自己，期待明天的自己。', category: 'growth' },
  { text: '在崩溃中重建，是最深刻的成长。', category: 'growth' },
  { text: '你已经熬过了很多个以为熬不过的夜晚。', category: 'growth' },
  { text: '生活会奖励那些不放弃的人。', category: 'growth' },
  { text: '变好的过程，往往是不动声色的。', category: 'growth' },
  { text: '你所经历的一切，正在让你变得独特。', category: 'growth' },
  { text: '把委屈和难过变成养分，默默成长。', category: 'growth' },
  { text: '那些没有打败你的，终将使你更强大。', category: 'growth' },
  { text: '给自己多一点耐心，成长需要时间。', category: 'growth' },
  { text: '最深的根，长在最暗的土壤里。', category: 'growth' },
  { text: '你正在经历的，正是你需要的功课。', category: 'growth' },
  { text: '别害怕重新开始，这一次你有了经验。', category: 'growth' },
  { text: '成长不是变得刀枪不入，而是学会自我疗愈。', category: 'growth' },
  { text: '生活从来不会辜负每一个认真的人。', category: 'growth' },
  { text: '你不是一无所有，你还有重新来过的勇气。', category: 'growth' },
  { text: '沉默的努力，终会被看见。', category: 'growth' },
  { text: '每一次心碎，都让心变得更宽广。', category: 'growth' },
  { text: '做自己的太阳，不必借别人的光。', category: 'growth' },
  { text: '你的节奏不必和别人一样。', category: 'growth' },
  { text: '选择成长，就是选择不断超越舒适圈。', category: 'growth' },
  { text: '从废墟中站起来的人，拥有最稳的根基。', category: 'growth' },
  { text: '学会独处，是成长的必修课。', category: 'growth' },
  { text: '一切都会好起来的，在你想不到的时候。', category: 'growth' },
  { text: '认识自己的不足，是智慧的开端。', category: 'growth' },
  { text: '你的坚持，终将美好。', category: 'growth' },
  { text: '放慢脚步不是退缩，是为了走得更远。', category: 'growth' },
  { text: '经历过深夜痛哭的人，才懂清晨的珍贵。', category: 'growth' },
  { text: '你今天的不安，是未来蜕变的序章。', category: 'growth' },
  { text: '把困境当成考验，你就已经通过了一半。', category: 'growth' },
  { text: '成长就是不断与过去的自己告别。', category: 'growth' },
  { text: '每一滴汗水，都在浇灌未来的花园。', category: 'growth' },
  { text: '你已经很棒了，只是还不知道而已。', category: 'growth' },
  { text: '在等待花开的日子里，先学会给自己浇水。', category: 'growth' },
  { text: '输得起的人，才赢得了人生。', category: 'growth' },
  { text: '温柔地对待自己的失败，是一种成熟。', category: 'growth' },
  { text: '黎明前最暗，但黎明一定会来。', category: 'growth' },
  { text: '人生的每一页，都值得被认真书写。', category: 'growth' },
  { text: '当你穿越了风暴，你就不再是从前的自己。', category: 'growth' },
  { text: '不要拿别人的地图，来走自己的路。', category: 'growth' },
  { text: '成长有时是安静的，只有自己知道。', category: 'growth' },
  { text: '你的眼泪从不会白流。', category: 'growth' },
  { text: '比起到达终点，出发本身就很了不起。', category: 'growth' },
  { text: '生活不会一直为难你，它只是在磨练你。', category: 'growth' },
  { text: '先学会爱自己，再去改变世界。', category: 'growth' },
  { text: '有些痛苦过后，你会感谢自己没有放弃。', category: 'growth' },
  { text: '成为更好的人，不必抛弃过去的自己。', category: 'growth' },
  { text: '你的潜力比你想象的大得多。', category: 'growth' },
  { text: '跌入谷底之后，每走一步都是向上。', category: 'growth' },
  { text: '学会在雨中跳舞，而不是等待雨停。', category: 'growth' },
  { text: '勇敢面对自己的软弱，就是最大的坚强。', category: 'growth' },
  { text: '成长不是一条直线，而是一圈圈的螺旋。', category: 'growth' },
  { text: '你的每一次挣扎，都在积蓄力量。', category: 'growth' },
  { text: '原谅过去的自己，是对未来最好的投资。', category: 'growth' },
  { text: '比昨天好一点点，就足够了。', category: 'growth' },
  { text: '所有的来日方长，都始于今天的一小步。', category: 'growth' },
  { text: '哭过之后擦干眼泪，继续赶路。', category: 'growth' },
  { text: '你值得被自己温柔以待。', category: 'growth' },
  { text: '成长的路上没有捷径，只有脚印。', category: 'growth' },
  { text: '让伤痕变成铠甲，而不是枷锁。', category: 'growth' },
  { text: '即使世界很暗，你也可以是自己的光。', category: 'growth' },
  { text: '不要因为走得慢而感到羞耻。', category: 'growth' },
  { text: '你的痛苦有意义，它在教会你什么。', category: 'growth' },
  { text: '所有的改变，都从接受现状开始。', category: 'growth' },
  { text: '勇敢地犯错，是学习最快的方式。', category: 'growth' },
  { text: '你正在书写属于自己的成长故事。', category: 'growth' },
  { text: '再小的进步，也值得被庆祝。', category: 'growth' },
  { text: '那些看似无用的日子，其实都在沉淀。', category: 'growth' },
  { text: '不必急于成为谁，先做好现在的自己。', category: 'growth' },
  { text: '每一次拒绝，都在引导你走向对的方向。', category: 'growth' },
  { text: '你不必一次成长到位，慢慢来也可以。', category: 'growth' },
  { text: '最好的投资，永远是投资自己。', category: 'growth' },
  { text: '痛过才知道什么最珍贵。', category: 'growth' },
  { text: '在混乱中找到自己的秩序。', category: 'growth' },
  { text: '你曾经以为过不去的坎，现在不都过来了吗。', category: 'growth' },
  { text: '成长是一场孤独但值得的旅行。', category: 'growth' },
  { text: '对自己诚实，是最勇敢的事。', category: 'growth' },
  { text: '把焦虑化为行动，你就赢了一半。', category: 'growth' },
  { text: '错过的风景，前方还会有更好的。', category: 'growth' },
  { text: '你不需要等到准备好了才出发。', category: 'growth' },
  { text: '成长是把期待别人变成相信自己。', category: 'growth' },
  { text: '光是想要改变这件事，就已经很了不起了。', category: 'growth' },
  { text: '在平凡的日子里，默默积蓄力量。', category: 'growth' },
  { text: '你的与众不同，就是你最大的优势。', category: 'growth' },
  { text: '允许自己偶尔脆弱，然后重新站起来。', category: 'growth' },
  { text: '未来的你，会感谢现在努力的自己。', category: 'growth' },
  { text: '不是所有的成长都需要被理解。', category: 'growth' },
  { text: '走出舒适圈的那一刻，你就在成长。', category: 'growth' },
  { text: '比起天赋，坚持更能决定结果。', category: 'growth' },
  { text: '你的存在本身，就是一种力量。', category: 'growth' },
  { text: '迷路的时候，就看看星星。', category: 'growth' },
  { text: '从今天起，做一个不怕犯错的人。', category: 'growth' },
  { text: '有些成长，需要在安静中完成。', category: 'growth' },
  { text: '你拥有重塑自己的无限可能。', category: 'growth' },
  { text: '困难只是暂时的，你的成长是永久的。', category: 'growth' },
  { text: '不要低估每一天的微小进步。', category: 'growth' },
  { text: '你是自己人生的唯一作者。', category: 'growth' },
  { text: '学会说不，也是成长的一部分。', category: 'growth' },
  { text: '你的价值不由别人的评价来定义。', category: 'growth' },
  { text: '在逆风中才能学会飞翔。', category: 'growth' },
  { text: '把遗憾变成动力，让未来不再后悔。', category: 'growth' },
  { text: '你已经在路上了，这就够了。', category: 'growth' },
  { text: '成长不怕晚，怕的是不开始。', category: 'growth' },
  { text: '接受不确定性，是最大的确定。', category: 'growth' },
  { text: '请相信那些暗暗努力的日子。', category: 'growth' },
  { text: '每一次深呼吸，都是重新开始的机会。', category: 'growth' },
  { text: '你的勇气比你的恐惧更强大。', category: 'growth' },
  { text: '不被理解也没关系，做你认为对的事。', category: 'growth' },
  { text: '人生最美的风景，往往在最难走的路上。', category: 'growth' },
  { text: '你正在变成小时候羡慕的那个大人。', category: 'growth' },
  { text: '成长就是学会在不完美中找到平衡。', category: 'growth' },
  { text: '每一个今天，都是未来最年轻的一天。', category: 'growth' },
  { text: '与其抱怨黑暗，不如自己点亮一盏灯。', category: 'growth' },
  { text: '你的坚韧，终将开花结果。', category: 'growth' },
  { text: '不要害怕重来，你已经比第一次更强了。', category: 'growth' },
  { text: '越过山丘的人，才能看见大海。', category: 'growth' },

  // ===== 情绪管理 (160条) =====
  { text: '情绪没有好坏之分，每种感受都值得被尊重。', category: 'emotion' },
  { text: '深呼吸，让自己慢下来。', category: 'emotion' },
  { text: '情绪就像天气，它会变化，也会过去。', category: 'emotion' },
  { text: '允许自己感受悲伤，这是疗愈的开始。', category: 'emotion' },
  { text: '你的感受是真实的，不需要向任何人解释。', category: 'emotion' },
  { text: '愤怒只是在告诉你，有些事情需要改变。', category: 'emotion' },
  { text: '放下对情绪的评判，只是静静地感受它。', category: 'emotion' },
  { text: '每一次呼吸都是重新开始的机会。', category: 'emotion' },
  { text: '情绪是身体给你的信号，试着去倾听它。', category: 'emotion' },
  { text: '让眼泪流下来吧，这是心灵在释放压力。', category: 'emotion' },
  { text: '此刻的不安终会过去，你比想象中更有韧性。', category: 'emotion' },
  { text: '不必急着好起来，慢慢来也没关系。', category: 'emotion' },
  { text: '把注意力带回当下，感受脚下的大地。', category: 'emotion' },
  { text: '你的情绪不能定义你是谁。', category: 'emotion' },
  { text: '焦虑是对未来的想象，试着回到此刻。', category: 'emotion' },
  { text: '感受情绪的流动，不抓取，不抗拒。', category: 'emotion' },
  { text: '内心的风暴终会平息，耐心等待晴天。', category: 'emotion' },
  { text: '慢慢吸气，慢慢呼气，让身体放松下来。', category: 'emotion' },
  { text: '你有权利说不，有权利保护自己的感受。', category: 'emotion' },
  { text: '情绪来了又走，你是那个不变的观察者。', category: 'emotion' },
  { text: '悲伤不是软弱，而是你曾深深在乎过。', category: 'emotion' },
  { text: '试着用好奇心看待自己的情绪变化。', category: 'emotion' },
  { text: '你不必独自承受一切，寻求帮助是勇敢的。', category: 'emotion' },
  { text: '此刻你是安全的，一切都会好起来。', category: 'emotion' },
  { text: '让心安静下来，听听内在的声音。', category: 'emotion' },
  { text: '每一种情绪都有它存在的理由。', category: 'emotion' },
  { text: '对自己说：我允许自己感受这一切。', category: 'emotion' },
  { text: '像水一样流动，不与情绪对抗。', category: 'emotion' },
  { text: '你的内心比你以为的更加强大。', category: 'emotion' },
  { text: '闭上眼睛，想象一个让你感到安全的地方。', category: 'emotion' },
  { text: '情绪是暂时的访客，让它来，也让它走。', category: 'emotion' },
  { text: '不要压抑感受，给它一个安全的出口。', category: 'emotion' },
  { text: '把手放在心口，感受自己的心跳。', category: 'emotion' },
  { text: '难过的时候，抱抱自己就好。', category: 'emotion' },
  { text: '学会与不确定性共处，这是成长的一部分。', category: 'emotion' },
  { text: '呼吸是你随时可以使用的平静工具。', category: 'emotion' },
  { text: '痛苦会过去，而经历会让你更加深刻。', category: 'emotion' },
  { text: '不是所有问题都需要立刻解决。', category: 'emotion' },
  { text: '给情绪一个名字，它就会变得不那么可怕。', category: 'emotion' },
  { text: '今天的你，只需要做到今天的最好就够了。', category: 'emotion' },
  { text: '放慢脚步，世界不会因此崩塌。', category: 'emotion' },
  { text: '你已经走过了很多困难的日子，这次也可以。', category: 'emotion' },
  { text: '用呼吸为自己创造一个宁静的空间。', category: 'emotion' },
  { text: '情绪不是你的敌人，它是你的信使。', category: 'emotion' },
  { text: '允许自己休息，这不是偷懒。', category: 'emotion' },
  { text: '试着像旁观者一样观察自己的情绪。', category: 'emotion' },
  { text: '哭泣是勇敢的，它意味着你在面对。', category: 'emotion' },
  { text: '在混乱中找到自己的呼吸节奏。', category: 'emotion' },
  { text: '你的心知道答案，给它时间去回应。', category: 'emotion' },
  { text: '温柔是一种力量，而不是一种弱点。', category: 'emotion' },
  { text: '现在感受到的一切，都是可以被接纳的。', category: 'emotion' },
  { text: '关注你能控制的事，放下你不能控制的。', category: 'emotion' },
  { text: '给自己的心灵放一天假吧。', category: 'emotion' },
  { text: '感受双脚踩在地面的踏实感。', category: 'emotion' },
  { text: '情绪的波浪会来也会走，你是那片海。', category: 'emotion' },
  { text: '对自己多一些耐心，改变需要时间。', category: 'emotion' },
  { text: '你可以同时感到害怕和勇敢。', category: 'emotion' },
  { text: '在安静中，你会找到内心的力量。', category: 'emotion' },
  { text: '不必为自己的感受感到抱歉。', category: 'emotion' },
  { text: '让思绪像云一样飘过，不必抓住。', category: 'emotion' },
  { text: '你比昨天更懂得如何照顾自己了。', category: 'emotion' },
  { text: '身体会记住压力，记得放松肩膀。', category: 'emotion' },
  { text: '真正的坚强，是敢于展示脆弱。', category: 'emotion' },
  { text: '情绪是流动的能量，让它自然通过。', category: 'emotion' },
  { text: '你正在经历的，很多人也经历过。', category: 'emotion' },
  { text: '给内心的小孩一些安慰和拥抱。', category: 'emotion' },
  { text: '没有人能永远快乐，这是正常的。', category: 'emotion' },
  { text: '试着把焦虑写下来，让它离开脑海。', category: 'emotion' },
  { text: '在呼与吸之间，找到属于你的宁静。', category: 'emotion' },
  { text: '接受帮助不是示弱，而是智慧。', category: 'emotion' },
  { text: '每个人都有不为人知的挣扎，善待自己。', category: 'emotion' },
  { text: '情绪低落时，先满足基本需求：吃饭、喝水、休息。', category: 'emotion' },
  { text: '你不欠任何人一个微笑。', category: 'emotion' },
  { text: '与其逃避情绪，不如坐下来陪伴它。', category: 'emotion' },
  { text: '感恩今天你还在这里，还在呼吸。', category: 'emotion' },
  { text: '别忘了，月亮也有阴晴圆缺。', category: 'emotion' },
  { text: '压力大的时候，先停下来喝一杯温水。', category: 'emotion' },
  { text: '你的情绪值得被看见，被理解。', category: 'emotion' },
  { text: '不必把所有事情都扛在肩上。', category: 'emotion' },
  { text: '安静地和自己待一会儿，也是一种充电。', category: 'emotion' },
  { text: '恐惧在提醒你边界在哪里。', category: 'emotion' },
  { text: '你有能力穿越这段困难的时光。', category: 'emotion' },
  { text: '对今天的自己说一声辛苦了。', category: 'emotion' },
  { text: '情绪管理不是消灭情绪，而是理解它。', category: 'emotion' },
  { text: '让阳光照进来，从打开窗户开始。', category: 'emotion' },
  { text: '有些路必须一个人走，但你并不孤单。', category: 'emotion' },
  { text: '伸展一下身体，释放积压的紧张感。', category: 'emotion' },
  { text: '做不到没关系，已经尽力就是最好的。', category: 'emotion' },
  { text: '生活不会永远这么难，相信时间的力量。', category: 'emotion' },
  { text: '学会在忙碌中给自己留白。', category: 'emotion' },
  { text: '你可以选择暂时离开让你不舒服的环境。', category: 'emotion' },
  { text: '内心的平静从接纳当下开始。', category: 'emotion' },
  { text: '情绪没有对错，行为才有选择。', category: 'emotion' },
  { text: '照顾好自己的情绪，才能更好地爱别人。', category: 'emotion' },
  { text: '感受微风拂过脸庞的温柔。', category: 'emotion' },
  { text: '你可以慢慢来，没有人在催你。', category: 'emotion' },
  { text: '把担忧交给明天，今天只需要好好休息。', category: 'emotion' },
  { text: '失落感在告诉你，你曾经拥有珍贵的东西。', category: 'emotion' },
  { text: '世界很大，你的烦恼只是其中一粒沙。', category: 'emotion' },
  { text: '用五感去感受当下：看、听、触、闻、尝。', category: 'emotion' },
  { text: '脆弱的时刻，恰恰是最需要自我关爱的时候。', category: 'emotion' },
  { text: '你值得拥有快乐，不需要任何理由。', category: 'emotion' },
  { text: '试着对镜子里的自己微笑一下。', category: 'emotion' },
  { text: '一步一步来，不需要一次解决所有问题。', category: 'emotion' },
  { text: '愤怒之下，往往藏着受伤和恐惧。', category: 'emotion' },
  { text: '你的眼泪浇灌着内心成长的种子。', category: 'emotion' },
  { text: '找到让你感到安心的那首歌，播放它。', category: 'emotion' },
  { text: '此刻的痛苦不会是永恒的。', category: 'emotion' },
  { text: '学会设立边界，保护自己的情绪空间。', category: 'emotion' },
  { text: '你的心灵花园需要定期浇灌和打理。', category: 'emotion' },
  { text: '深吸一口气，数到四，再慢慢呼出。', category: 'emotion' },
  { text: '不喜欢的事情可以拒绝，这是你的权利。', category: 'emotion' },
  { text: '和信任的人聊聊天，分担不会让痛苦加倍。', category: 'emotion' },
  { text: '你不必理解所有的感受，接受就好。', category: 'emotion' },
  { text: '即使在黑暗中，你的光也不会熄灭。', category: 'emotion' },
  { text: '拥抱你的不完美，那是独特的印记。', category: 'emotion' },
  { text: '记住那些让你微笑的小事。', category: 'emotion' },
  { text: '你的身体在替你承受情绪，关心它吧。', category: 'emotion' },
  { text: '困难时刻恰恰是成长最快的时候。', category: 'emotion' },
  { text: '让自己被温暖的事物包围。', category: 'emotion' },
  { text: '不必与他人比较，你有自己的节奏。', category: 'emotion' },
  { text: '情绪需要出口，写日记是一种好方式。', category: 'emotion' },
  { text: '你可以同时感到感恩和悲伤。', category: 'emotion' },
  { text: '在自然中散步，让大地帮你接地。', category: 'emotion' },
  { text: '允许自己拥有一段什么都不做的时间。', category: 'emotion' },
  { text: '愧疚感在提醒你内心的价值观。', category: 'emotion' },
  { text: '你的感受是合理的，即使别人不理解。', category: 'emotion' },
  { text: '在混乱中寻找一件让你感到平静的事。', category: 'emotion' },
  { text: '不必总是微笑，真实的表情也很美。', category: 'emotion' },
  { text: '当情绪翻涌时，先照顾好身体。', category: 'emotion' },
  { text: '你有权利为自己的幸福做出选择。', category: 'emotion' },
  { text: '试着把注意力从头脑带到心里。', category: 'emotion' },
  { text: '孤独感在提醒你渴望连接，去找找温暖。', category: 'emotion' },
  { text: '情绪的洪水会退去，你只需要坚持住。', category: 'emotion' },
  { text: '善待自己的方式有很多，今天选一种吧。', category: 'emotion' },
  { text: '你的心有自我修复的能力，给它时间。', category: 'emotion' },
  { text: '感到迷茫也没关系，路会慢慢清晰。', category: 'emotion' },
  { text: '在感到无力时，做一件小事就是胜利。', category: 'emotion' },
  { text: '嫉妒在告诉你内心真正想要什么。', category: 'emotion' },
  { text: '你不需要所有人都喜欢你。', category: 'emotion' },
  { text: '静静地坐着，让呼吸带走紧张。', category: 'emotion' },
  { text: '每一段经历都在塑造更完整的你。', category: 'emotion' },
  { text: '委屈的时候，允许自己大哭一场。', category: 'emotion' },
  { text: '你有足够的智慧去处理眼前的困境。', category: 'emotion' },
  { text: '羞耻感很重，但它不是你的全部。', category: 'emotion' },
  { text: '今天只做让心感到温暖的事。', category: 'emotion' },
  { text: '放下手机，闭上眼睛，和自己独处片刻。', category: 'emotion' },
  { text: '你的情绪日记是送给未来自己的礼物。', category: 'emotion' },

  // ===== 人生哲理 (160条) =====
  { text: '人生没有白走的路，每一步都算数。', category: 'life' },
  { text: '最好的时光，是现在。', category: 'life' },
  { text: '你来人间一趟，要看看太阳。', category: 'life' },
  { text: '生活不会辜负每一个努力的人。', category: 'life' },
  { text: '花开不是为了花落，而是为了绽放。', category: 'life' },
  { text: '人间值得，未来可期。', category: 'life' },
  { text: '每一天都是重新开始的机会。', category: 'life' },
  { text: '生命的意义在于体验，而非完美。', category: 'life' },
  { text: '你不必活成别人期待的样子。', category: 'life' },
  { text: '平凡的日子里藏着最真实的幸福。', category: 'life' },
  { text: '走过的弯路，也是必经之路。', category: 'life' },
  { text: '世间万物皆有裂缝，那是光照进来的地方。', category: 'life' },
  { text: '活着本身就是一件值得庆祝的事。', category: 'life' },
  { text: '人生海海，山山而川。', category: 'life' },
  { text: '不完美的人生，才是真实的人生。', category: 'life' },
  { text: '日子是过以后才知道好的。', category: 'life' },
  { text: '把每一个平凡的日子过成诗。', category: 'life' },
  { text: '生活的答案藏在生活本身里。', category: 'life' },
  { text: '你值得拥有世间一切美好。', category: 'life' },
  { text: '人生苦短，及时行乐，及时行善。', category: 'life' },
  { text: '岁月不居，时节如流，且行且珍惜。', category: 'life' },
  { text: '简单生活，才是最高级的奢侈。', category: 'life' },
  { text: '所有的遇见，都是久别重逢。', category: 'life' },
  { text: '人生就像一本书，翻过这页还有下页。', category: 'life' },
  { text: '与其追赶时间，不如享受当下。', category: 'life' },
  { text: '生活明朗，万物可爱。', category: 'life' },
  { text: '人间烟火气，最抚凡人心。', category: 'life' },
  { text: '没有一个冬天不可逾越。', category: 'life' },
  { text: '所有失去的，都会以另一种方式归来。', category: 'life' },
  { text: '不必追赶日落，因为明天太阳还会升起。', category: 'life' },
  { text: '你的存在本身就是一种意义。', category: 'life' },
  { text: '生命是一场旅行，不是一场赛跑。', category: 'life' },
  { text: '世界很大，幸福很小，刚好你都拥有。', category: 'life' },
  { text: '日出之美在于它脱胎于最深的黑暗。', category: 'life' },
  { text: '你走过的每条路都有它的风景。', category: 'life' },
  { text: '认真生活的人，生活绝不会亏待你。', category: 'life' },
  { text: '人生如逆旅，我亦是行人。', category: 'life' },
  { text: '生活总会在你不经意间变得美好。', category: 'life' },
  { text: '一切都是最好的安排。', category: 'life' },
  { text: '把心放宽，世界就会变大。', category: 'life' },
  { text: '时间会证明，你所有的坚持都有意义。', category: 'life' },
  { text: '生活的美好，在于发现和感受。', category: 'life' },
  { text: '别急，属于你的风景终会出现。', category: 'life' },
  { text: '平淡是生活的底色，也是最持久的美。', category: 'life' },
  { text: '来日方长，细水长流。', category: 'life' },
  { text: '你要相信，所有的好事都在路上。', category: 'life' },
  { text: '人活一世，快乐是真，其余都是浮云。', category: 'life' },
  { text: '最珍贵的不是拥有多少，而是感受多少。', category: 'life' },
  { text: '在人间，有事做，有人爱，有所期待。', category: 'life' },
  { text: '生命太短，没时间留给遗憾。', category: 'life' },
  { text: '热爱生活的人，终将被生活热爱。', category: 'life' },
  { text: '顺其自然，是对生活最大的温柔。', category: 'life' },
  { text: '人这一生，要学会和自己和解。', category: 'life' },
  { text: '万事皆有期，不负当下即是最好的珍惜。', category: 'life' },
  { text: '星星发光是为了让每个人找到回家的路。', category: 'life' },
  { text: '活在此刻，便是永恒。', category: 'life' },
  { text: '人间有味是清欢。', category: 'life' },
  { text: '不必事事如意，但求事事尽心。', category: 'life' },
  { text: '你是自己人生唯一的主角。', category: 'life' },
  { text: '生活的真谛是学会与不完美共处。', category: 'life' },
  { text: '路虽远，行则将至。', category: 'life' },
  { text: '温柔地对待生活，生活也会温柔地待你。', category: 'life' },
  { text: '每一段经历都是生命赠予的礼物。', category: 'life' },
  { text: '人生的路，要自己走才有意义。', category: 'life' },
  { text: '慢一点也没关系，重要的是不停下。', category: 'life' },
  { text: '用心感受，生活处处是风景。', category: 'life' },
  { text: '凡是过往，皆为序章。', category: 'life' },
  { text: '生活不止眼前的苟且，还有诗和远方。', category: 'life' },
  { text: '世间所有美好都值得等待。', category: 'life' },
  { text: '人生没有标准答案，快乐就好。', category: 'life' },
  { text: '接受不完美，是走向完整的第一步。', category: 'life' },
  { text: '每一次呼吸都是生命的馈赠。', category: 'life' },
  { text: '别为难自己，毕竟人间不易。', category: 'life' },
  { text: '做自己，是最不费力的活法。', category: 'life' },
  { text: '生活的节奏，由你自己来定。', category: 'life' },
  { text: '山高水长，来日可期。', category: 'life' },
  { text: '四季轮转，每一季都有它的美。', category: 'life' },
  { text: '人生如茶，苦后回甘。', category: 'life' },
  { text: '幸福不在远方，就在你身边。', category: 'life' },
  { text: '向前走，不回头，前方自有光。', category: 'life' },
  { text: '岁月漫长，然而值得等待。', category: 'life' },
  { text: '每一个清晨都是新生活的邀请函。', category: 'life' },
  { text: '内心丰盈的人，无惧岁月流逝。', category: 'life' },
  { text: '人这一辈子，最重要的是活出自己。', category: 'life' },
  { text: '眼里有光的人，心里一定有爱。', category: 'life' },
  { text: '人生是旷野，不是轨道。', category: 'life' },
  { text: '简单的幸福，最难得也最长久。', category: 'life' },
  { text: '允许一切发生，是最大的智慧。', category: 'life' },
  { text: '今天的你，是昨天的你努力的结果。', category: 'life' },
  { text: '每条河流都有自己的方向和节奏。', category: 'life' },
  { text: '学会放下，才能轻装前行。', category: 'life' },
  { text: '繁花似锦觅安宁，淡云流水度此生。', category: 'life' },
  { text: '你所热爱的，终将成就你。', category: 'life' },
  { text: '人间草木深，处处皆温情。', category: 'life' },
  { text: '放慢脚步，才能听到花开的声音。', category: 'life' },
  { text: '生命的长度有限，宽度由你决定。', category: 'life' },
  { text: '走自己的路，看自己的风景。', category: 'life' },
  { text: '活着就有无限可能。', category: 'life' },
  { text: '时光不负有心人。', category: 'life' },
  { text: '安静地努力，悄悄地变好。', category: 'life' },
  { text: '人生处处是起点，时时可重来。', category: 'life' },
  { text: '你的善良，终会回馈于你。', category: 'life' },
  { text: '珍惜当下的每一份小确幸。', category: 'life' },
  { text: '一花一世界，一叶一菩提。', category: 'life' },
  { text: '所有的付出都不会被辜负。', category: 'life' },
  { text: '有些路看起来很远，走着走着就到了。', category: 'life' },
  { text: '用感恩的心过好每一天。', category: 'life' },
  { text: '风雨过后，总会有彩虹。', category: 'life' },
  { text: '人生最曼妙的风景是内心的淡定与从容。', category: 'life' },
  { text: '不慌不忙，也能抵达想去的远方。', category: 'life' },
  { text: '生活给你柠檬，你就酿成蜜。', category: 'life' },
  { text: '愿你眼中有星辰，心中有山海。', category: 'life' },
  { text: '每一朵花都会按时盛开。', category: 'life' },
  { text: '你的人生，由你书写。', category: 'life' },
  { text: '种下善意的种子，静待花开。', category: 'life' },
  { text: '人间一趟，尽兴而归。', category: 'life' },
  { text: '心若向阳，何惧忧伤。', category: 'life' },
  { text: '生命中的每一天都不可复制。', category: 'life' },
  { text: '知足常乐，是最朴素的幸福。', category: 'life' },
  { text: '你正在成为你想成为的人。', category: 'life' },
  { text: '大地回春，万物有时。', category: 'life' },
  { text: '和喜欢的一切在一起，就是好日子。', category: 'life' },
  { text: '把日子过成自己想要的样子。', category: 'life' },
  { text: '心存美好，则无可恼之事。', category: 'life' },
  { text: '每个人都在发着光，只是有时自己看不到。', category: 'life' },
  { text: '生活虽有不如意，但仍值得热爱。', category: 'life' },
  { text: '水到渠成，瓜熟蒂落，凡事自有定数。', category: 'life' },
  { text: '做一个温暖的人，不求深刻，只求简单。', category: 'life' },
  { text: '万般滋味，皆是生活。', category: 'life' },
  { text: '人生百味，甘苦自知，皆是收获。', category: 'life' },
  { text: '风吹过的地方，都有花香。', category: 'life' },
  { text: '此刻的你，已经足够好了。', category: 'life' },
  { text: '人生如画，浓淡相宜。', category: 'life' },
  { text: '每一段路都有属于它的意义。', category: 'life' },
  { text: '生命的精彩在于未知和探索。', category: 'life' },
  { text: '你所经历的一切，都让你更加完整。', category: 'life' },
  { text: '细微之处见真章，平凡之中见伟大。', category: 'life' },
  { text: '人生就是不断地放下与拿起。', category: 'life' },
  { text: '心安即是归处。', category: 'life' },
  { text: '好好吃饭，好好睡觉，好好生活。', category: 'life' },
  { text: '你无法改变风向，但可以调整船帆。', category: 'life' },
  { text: '世上没有白费的努力，也没有白来的成功。', category: 'life' },
  { text: '生活是一面镜子，你笑它也笑。', category: 'life' },
  { text: '有些美好，只在回头时才看得见。', category: 'life' },
  { text: '带着希望出发，沿途都是风景。', category: 'life' },
  { text: '接纳自己的节奏，不必与他人比较。', category: 'life' },
  { text: '春风十里，不如当下的你。', category: 'life' },
  { text: '人生如梦，但值得认真去做。', category: 'life' },
  { text: '一切终将过去，美好终将到来。', category: 'life' },
  { text: '生活不在别处，就在此时此地。', category: 'life' },
  { text: '你是这世间独一无二的风景。', category: 'life' },
  { text: '踏实走好每一步，不辜负每一天。', category: 'life' },
  { text: '生命的温度，来自人与人之间的连接。', category: 'life' },
  { text: '万物皆有缝隙，不必追求滴水不漏。', category: 'life' },
  { text: '你的故事才刚刚开始，别着急翻到结局。', category: 'life' },
  { text: '平平淡淡才是真，简简单单才是福。', category: 'life' },
];

// 获取每日语录（基于日期的确定性选择）
export function getDailyQuote(): HealingQuote {
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / 86400000
  );
  return HEALING_QUOTES[dayOfYear % HEALING_QUOTES.length];
}

// 获取随机语录
export function getRandomQuote(category?: HealingQuote['category']): HealingQuote {
  const pool = category
    ? HEALING_QUOTES.filter(q => q.category === category)
    : HEALING_QUOTES;
  return pool[Math.floor(Math.random() * pool.length)];
}

// 按分类获取语录
export function getQuotesByCategory(category: HealingQuote['category']): HealingQuote[] {
  return HEALING_QUOTES.filter(q => q.category === category);
}

// ========== 失恋疗愈五阶段 ==========
export interface HealingStage {
  id: number;
  name: string;
  emoji: string;
  color: string;
  bgColor: string;
  title: string;
  description: string;
  tips: string[];
  affirmations: string[];
}

export const HEARTBREAK_STAGES: HealingStage[] = [
  {
    id: 1,
    name: '否认',
    emoji: '😶',
    color: '#6B7280',
    bgColor: '#F3F4F6',
    title: '第一阶段：否认期',
    description: '你可能还无法相信这段感情已经结束，觉得对方会回来，或者这一切只是一场梦。这是正常的自我保护机制。',
    tips: [
      '允许自己感到困惑和不真实感',
      '不要急着做任何重大决定',
      '暂时不要联系前任，给自己空间',
      '告诉至少一个信任的朋友你的状况',
      '记录下你现在的感受，以后回看会发现自己的成长',
    ],
    affirmations: [
      '我允许自己慢慢接受这个事实。',
      '感到不真实是正常的，我不必急于面对一切。',
      '我有足够的时间来消化这件事。',
    ],
  },
  {
    id: 2,
    name: '愤怒',
    emoji: '😤',
    color: '#EF4444',
    bgColor: '#FEE2E2',
    title: '第二阶段：愤怒期',
    description: '你可能会感到愤怒——对对方、对自己、甚至对整个世界。这份愤怒其实是你在保护自己受伤的心。',
    tips: [
      '愤怒是健康的情绪，不要压抑它',
      '找安全的方式释放：运动、大声唱歌、写信（不发出去）',
      '避免在社交媒体上发泄或公开指责',
      '不要通过报复来缓解愤怒，这只会让你更痛苦',
      '试着把愤怒写在日记里，让它有一个出口',
    ],
    affirmations: [
      '我的愤怒是有理由的，我被允许生气。',
      '我选择用健康的方式释放这些情绪。',
      '愤怒过后，我会找到平静。',
    ],
  },
  {
    id: 3,
    name: '悲伤',
    emoji: '😢',
    color: '#3B82F6',
    bgColor: '#DBEAFE',
    title: '第三阶段：悲伤期',
    description: '深深的悲伤和失落感会席卷而来。你可能会频繁哭泣、失眠、没有食欲。这是疗愈必经之路。',
    tips: [
      '想哭就哭，不要觉得丢人',
      '保持基本的生活作息：吃饭、睡觉、洗澡',
      '听一些舒缓的音乐，看看治愈的电影',
      '出去散步，感受阳光和新鲜空气',
      '整理掉与前任相关的物品（可以先装箱，不必扔掉）',
      '如果悲伤持续严重影响生活，请寻求专业帮助',
    ],
    affirmations: [
      '悲伤说明我曾经真心爱过，这不可耻。',
      '眼泪是心灵的清洗，哭过之后会更轻松。',
      '这份痛苦是暂时的，它终将过去。',
    ],
  },
  {
    id: 4,
    name: '接受',
    emoji: '😌',
    color: '#8B5CF6',
    bgColor: '#EDE9FE',
    title: '第四阶段：接受期',
    description: '你开始慢慢接受分手的事实。虽然偶尔还会难过，但你开始能够正常生活，甚至觉得一个人也不错。',
    tips: [
      '开始重新规划自己的生活',
      '尝试一个新的爱好或学一项新技能',
      '重新建立社交圈，多和朋友相处',
      '反思这段感情教会了你什么',
      '写一封给自己的信，感谢自己的坚强',
    ],
    affirmations: [
      '我接受这段感情已经结束的事实。',
      '我从这段经历中学到了很多。',
      '没有他/她，我的人生依然精彩。',
    ],
  },
  {
    id: 5,
    name: '重生',
    emoji: '🌟',
    color: '#10B981',
    bgColor: '#D1FAE5',
    title: '第五阶段：重生期',
    description: '你已经走出来了！你变得更了解自己，更知道自己想要什么。你准备好迎接新的生活和新的爱情。',
    tips: [
      '庆祝自己的成长和勇敢',
      '保持写日记的习惯，持续关注自己的情绪',
      '不要急着进入下一段感情，等你真正准备好',
      '分享你的经验，帮助正在经历同样痛苦的人',
      '记住：你值得被好好爱',
    ],
    affirmations: [
      '我已经成为了更好的自己。',
      '我值得拥有真正的幸福和爱。',
      '过去的经历让我更懂得珍惜。',
      '新的旅程正在等着我。',
    ],
  },
];

// ========== 情绪智能回复 ==========
export interface MoodResponse {
  moodTag: string;
  responses: string[];
}

export const MOOD_RESPONSES: MoodResponse[] = [
  {
    moodTag: 'missing',
    responses: [
      '想念一个人说明你们之间有过真实的连接。允许自己想念，但也要允许自己前行。',
      '想念的感觉很难受，但它也说明你有一颗柔软的心。抱抱你。',
      '把想念写下来，是一种很好的释放方式。你做得很好。',
      '想念会慢慢变淡的，就像潮水一样，总会退去。',
    ],
  },
  {
    moodTag: 'pain',
    responses: [
      '你正在经历的痛苦是真实的，我看到了。你不必假装坚强。',
      '痛苦的感觉很难熬，但请相信，你比自己想象的更坚强。',
      '今天能把感受写下来，已经是很勇敢的一步了。',
      '给自己多一些温柔吧，你已经很努力了。',
    ],
  },
  {
    moodTag: 'anger',
    responses: [
      '生气是正常的情绪反应，你有权利生气。试着深呼吸，让愤怒慢慢流过。',
      '把愤怒写出来是很好的选择，比发给对方好得多。你很明智。',
      '愤怒的背后往往藏着更深的情绪。等平静后，可以再想想这份怒气是什么。',
      '你的愤怒是有理由的。但记得，放下不是为了对方，是为了自己。',
    ],
  },
  {
    moodTag: 'relief',
    responses: [
      '太好了！能感到释怀是疗愈的重要标志。为你开心！',
      '释怀不容易，你走到这一步真的很了不起。',
      '轻松的感觉真好。记住这一刻，以后难过的时候可以回来看看。',
      '放下是送给自己最好的礼物。你做到了！',
    ],
  },
  {
    moodTag: 'regret',
    responses: [
      '每个人都会有遗憾，这说明你在反思和成长。',
      '后悔说明你在乎，但不要因此责怪自己太多。你当时做了最好的选择。',
      '过去的事情无法改变，但你可以选择如何面对未来。',
      '把遗憾变成经验，下一次你会做得更好。',
    ],
  },
  {
    moodTag: 'calm',
    responses: [
      '平静是一种力量。享受这份宁静吧。',
      '在平静中写下的文字，往往最接近内心。你做得很好。',
      '今天的你看起来很安定。继续保持这份从容。',
      '能够平静地面对生活，本身就是一种了不起的能力。',
    ],
  },
  {
    moodTag: 'gratitude',
    responses: [
      '感恩的心让生活更美好。谢谢你记录下这份感动。',
      '懂得感恩的人，运气总不会太差。',
      '在感恩中找到快乐，是最简单的幸福秘诀。',
      '今天一定发生了温暖的事吧。谢谢你和这里分享。',
    ],
  },
];

// 根据心情标签获取智能回复
export function getMoodReply(moodTag: string, moodScore: number): string {
  const moodData = MOOD_RESPONSES.find(m => m.moodTag === moodTag);
  if (!moodData) {
    return '谢谢你记录今天的心情。每一天的记录都是对自己的关爱。';
  }

  let prefix = '';
  if (moodScore <= 3) {
    prefix = '今天似乎很不容易。';
  } else if (moodScore <= 5) {
    prefix = '';
  } else if (moodScore >= 8) {
    prefix = '看起来今天心情不错！';
  }

  const responses = moodData.responses;
  const idx = Math.floor(Math.random() * responses.length);
  return prefix ? `${prefix}${responses[idx]}` : responses[idx];
}

// 语录分类名称映射
export const CATEGORY_LABELS: Record<HealingQuote['category'], { label: string; emoji: string }> = {
  warmth: { label: '温暖治愈', emoji: '🤗' },
  heartbreak: { label: '失恋疗愈', emoji: '💔' },
  'self-love': { label: '自我肯定', emoji: '💪' },
  growth: { label: '成长感悟', emoji: '🌱' },
  emotion: { label: '情绪管理', emoji: '🧘' },
  life: { label: '人生哲理', emoji: '✨' },
};
